package com.br.fatecswing.view;

import com.br.fatecswing.dao.cidadeDAO;
import com.br.fatecswing.model.ModeloCidade;
import com.br.fatecswing.util.ModeloTabela;
import com.br.fatecswing.util.SingleConnection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

public class FormCidade extends javax.swing.JFrame {
    SingleConnection conexao;
    ModeloCidade modelo = new ModeloCidade();
    cidadeDAO cidade = new cidadeDAO();
    SingleConnection conexaoBanco;

    /**
     * Creates new form FormCidade
     */
    public FormCidade() {
        initComponents();
        try {
            conexao = new SingleConnection();
            conexao.conectar();
        } catch (Exception ex) {
            System.out.println("Erro ao conectar com o Banco! Erro: "+ex.getMessage());
            ex.printStackTrace();
        }
        preecherCombo();
        preencherTabelaCidade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNomeCidade = new javax.swing.JTextField();
        jButtonAdicionarEstados = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCidades = new javax.swing.JTable();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jComboBoxSituacao = new javax.swing.JComboBox<>();
        jTextFieldCodigoCidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de cidades");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome da cidade: ");

        jLabel3.setText("Situação:");

        jLabel4.setText("Estado:");

        jTextFieldNomeCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeCidadeActionPerformed(evt);
            }
        });

        jButtonAdicionarEstados.setText("Add");
        jButtonAdicionarEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarEstadosActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Deletar");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jTableCidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCidadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCidades);

        jComboBoxEstado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jComboBoxEstadoMouseMoved(evt);
            }
        });
        jComboBoxEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxEstadoMouseClicked(evt);
            }
        });
        jComboBoxEstado.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jComboBoxEstadoComponentShown(evt);
            }
        });
        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });

        jComboBoxSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        jComboBoxSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSituacaoActionPerformed(evt);
            }
        });

        jTextFieldCodigoCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoCidadeActionPerformed(evt);
            }
        });

        jLabel5.setText("Codigo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldCodigoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonNovo)
                                .addGap(9, 9, 9)
                                .addComponent(jButtonSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonExcluir)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAdicionarEstados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarEstados)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodigoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro De Cidades");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(252, 252, 252))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonAdicionarEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarEstadosActionPerformed
        // TODO add your handling code here:
        FrmEstado frm = new FrmEstado();
        frm.show();
    }//GEN-LAST:event_jButtonAdicionarEstadosActionPerformed

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

    private void jComboBoxEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxEstadoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxEstadoMouseClicked

    private void jComboBoxEstadoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboBoxEstadoComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoComponentShown

    private void jComboBoxEstadoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxEstadoMouseMoved
        // TODO add your handling code here:
        preecherCombo();
    }//GEN-LAST:event_jComboBoxEstadoMouseMoved

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        modelo.setNome(jTextFieldNomeCidade.getText());
        modelo.setSituacao(String.valueOf(jComboBoxSituacao.getSelectedItem()));
        if (String.valueOf(jComboBoxSituacao.getSelectedItem()).equals("Ativo")) {
            modelo.setSituacao("A");
        } else {
            modelo.setSituacao("B");
        }
        modelo.setSigla(String.valueOf(jComboBoxEstado.getSelectedItem()));
        cidade.InserirCidade(modelo);
        jTableCidades.removeAll();
        preencherTabelaCidade();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        jTextFieldCodigoCidade.setText("");
        jTextFieldNomeCidade.setText("");
        jComboBoxSituacao.addItem("");
        jComboBoxEstado.addItem("");
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        // passa para o modelo os dados necessários para
        // alterar no banco e depois passa o modelo preenchido
        // para o objeto est, que faz as alterações dos dados
        modelo.setNome(jTextFieldNomeCidade.getText());
        modelo.setSituacao(String.valueOf(jComboBoxSituacao.getSelectedItem()));
        System.out.println("Passei aqui.");
        if (String.valueOf(jComboBoxSituacao.getSelectedItem()).equals("Ativo")) {
            modelo.setSituacao("A");
        } else {
            modelo.setSituacao("B");
        }
        modelo.setSigla(String.valueOf(jComboBoxEstado.getSelectedItem()));
        modelo.setCodigo(Integer.parseInt(jTextFieldCodigoCidade.getText()));
        cidade.alterarCidade(modelo);
        jTableCidades.removeAll();
        preencherTabelaCidade();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jTextFieldNomeCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeCidadeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldNomeCidadeActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        // passa para o modelo os dados necessarios para 
        //excluir no banco e depois passa o modelo preenchido para
        // o objeto est, que faz a exclusão dos dados
        modelo.setCodigo(Integer.parseInt(jTextFieldCodigoCidade.getText()));
        modelo.setNome(jTextFieldNomeCidade.getText());
        modelo.setSituacao(String.valueOf(jComboBoxSituacao.getSelectedItem()));
        modelo.setSigla(String.valueOf(jComboBoxEstado.getSelectedItem()));
        cidade.ExcluirCidade(modelo);
        jTableCidades.removeAll();
        preencherTabelaCidade();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableCidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCidadesMouseClicked
        // TODO add your handling code here:
        jTextFieldCodigoCidade.setText("" + String.valueOf(jTableCidades.getValueAt(jTableCidades.getSelectedRow(), 0)));
        jTextFieldNomeCidade.setText("" + String.valueOf(jTableCidades.getValueAt(jTableCidades.getSelectedRow(), 1)));
        jComboBoxEstado.addItem("" + String.valueOf(jTableCidades.getValueAt(jTableCidades.getSelectedRow(), 2)));
    }//GEN-LAST:event_jTableCidadesMouseClicked

    private void jComboBoxSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSituacaoActionPerformed

    private void jTextFieldCodigoCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoCidadeActionPerformed

    public void preecherCombo() {
        jComboBoxEstado.removeAllItems();
        try {
            conexao.excutaSQL("select * from estado order by siglaestado");
            conexao.resultset.first();
            do {
                jComboBoxEstado.addItem(conexao.resultset.getString("siglaestado"));
            } while (conexao.resultset.next());

            //conexao.desconetaBanco();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher a combo!\nErro: " + ex.getMessage());
            ex.getStackTrace();
        }

    }

    public void preencherTabelaCidade() {
        ArrayList dados = new ArrayList();
        // Criação de Array para a inserção dos títulos no cabeçalho
        String[] colunas = new String[]{"Código", "Cidade", "Sigla Estado"};
        try {
            conexaoBanco = new SingleConnection();
            conexaoBanco.conectar();
            conexaoBanco.excutaSQL("select * from cidade inner join estado on cidade.idestado = estado.idestado order by cidade");
            conexaoBanco.resultset.first();
            do {
                dados.add(new Object[]{new Integer(Integer.parseInt(conexaoBanco.resultset.getString("idcidade"))), conexaoBanco.resultset.getString("nomecidade"), conexaoBanco.resultset.getString("siglaestado")});
            } while (conexaoBanco.resultset.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "OPA! Nenhum registro cadastrado.", "AVISO", JOptionPane.WARNING_MESSAGE);
        }

        //Criando tabela
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableCidades.setModel(modelo);
        jTableCidades.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableCidades.getColumnModel().getColumn(0).setResizable(false);
        jTableCidades.getColumnModel().getColumn(1).setPreferredWidth(400);
        jTableCidades.getColumnModel().getColumn(1).setResizable(true);
        jTableCidades.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTableCidades.getColumnModel().getColumn(2).setResizable(true);
        jTableCidades.getTableHeader().setReorderingAllowed(false);
        jTableCidades.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableCidades.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarEstados;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxSituacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTableCidades;
    private javax.swing.JTextField jTextFieldCodigoCidade;
    private javax.swing.JTextField jTextFieldNomeCidade;
    // End of variables declaration//GEN-END:variables
}
